development:
  :concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 15
:queues:
  - entity_management
  - download_csv
  - kinesis
  - tracking
  - default
  - api_pull
  - stat_management
  - mailers
  - email_notification
  - searchkick
  - cdn
  - elasticsearch
  - maintenance
