class AddContinentToCountries < ActiveRecord::Migration[6.1]
  def up
    add_column :countries, :continent, :string

    [
      { country: 'Albania', continent: 'Europe' },
      { country: 'Algeria', continent: 'Africa' },
      { country: 'Argentina', continent: 'South America' },
      { country: 'Australia', continent: 'Oceania' },
      { country: 'Austria', continent: 'Europe' },
      { country: 'Bahrain', continent: 'Asia' },
      { country: 'Bangladesh', continent: 'Asia' },
      { country: 'Belarus', continent: 'Europe' },
      { country: 'Belgium', continent: 'Europe' },
      { country: 'Bolivia', continent: 'South America' },
      { country: 'Brazil', continent: 'South America' },
      { country: 'Bulgaria', continent: 'Europe' },
      { country: 'Canada', continent: 'North America' },
      { country: 'Chile', continent: 'South America' },
      { country: 'China', continent: 'Asia' },
      { country: 'Colombia', continent: 'South America' },
      { country: 'Costa Rica', continent: 'North America' },
      { country: 'Croatia', continent: 'Europe' },
      { country: 'Cyprus', continent: 'Europe' },
      { country: 'Denmark', continent: 'Europe' },
      { country: 'Dominican Republic', continent: 'North America' },
      { country: 'Ecuador', continent: 'South America' },
      { country: 'Egypt', continent: 'Africa' },
      { country: 'El Salvador', continent: 'North America' },
      { country: 'Estonia', continent: 'Europe' },
      { country: 'Finland', continent: 'Europe' },
      { country: 'France', continent: 'Europe' },
      { country: 'Georgia', continent: 'Europe' },
      { country: 'Germany', continent: 'Europe' },
      { country: 'Ghana', continent: 'Africa' },
      { country: 'Greece', continent: 'Europe' },
      { country: 'Guatemala', continent: 'North America' },
      { country: 'Haiti', continent: 'North America' },
      { country: 'Honduras', continent: 'North America' },
      { country: 'Hungary', continent: 'Europe' },
      { country: 'Iceland', continent: 'Europe' },
      { country: 'India', continent: 'Asia' },
      { country: 'Indonesia', continent: 'Asia' },
      { country: 'Iran', continent: 'Asia' },
      { country: 'Iraq', continent: 'Asia' },
      { country: 'Ireland', continent: 'Europe' },
      { country: 'Israel', continent: 'Asia' },
      { country: 'Italy', continent: 'Europe' },
      { country: 'Japan', continent: 'Asia' },
      { country: 'Jordan', continent: 'Asia' },
      { country: 'Kenya', continent: 'Africa' },
      { country: 'Kuwait', continent: 'Asia' },
      { country: 'Lebanon', continent: 'Asia' },
      { country: 'Luxembourg', continent: 'Europe' },
      { country: 'Macedonia', continent: 'Europe' },
      { country: 'Malaysia', continent: 'Asia' },
      { country: 'Mexico', continent: 'North America' },
      { country: 'Netherlands', continent: 'Europe' },
      { country: 'New Zealand', continent: 'Oceania' },
      { country: 'Nicaragua', continent: 'North America' },
      { country: 'Nigeria', continent: 'Africa' },
      { country: 'Norway', continent: 'Europe' },
      { country: 'Oman', continent: 'Asia' },
      { country: 'Panama', continent: 'North America' },
      { country: 'Paraguay', continent: 'South America' },
      { country: 'Peru', continent: 'South America' },
      { country: 'Philippines', continent: 'Asia' },
      { country: 'Poland', continent: 'Europe' },
      { country: 'Portugal', continent: 'Europe' },
      { country: 'Qatar', continent: 'Asia' },
      { country: 'Romania', continent: 'Europe' },
      { country: 'Saudi Arabia', continent: 'Asia' },
      { country: 'Singapore', continent: 'Asia' },
      { country: 'Slovakia', continent: 'Europe' },
      { country: 'Slovenia', continent: 'Europe' },
      { country: 'South Africa', continent: 'Africa' },
      { country: 'Spain', continent: 'Europe' },
      { country: 'Sri Lanka', continent: 'Asia' },
      { country: 'Sweden', continent: 'Europe' },
      { country: 'Switzerland', continent: 'Europe' },
      { country: 'Thailand', continent: 'Asia' },
      { country: 'Turkey', continent: 'Asia' },
      { country: 'Ukraine', continent: 'Europe' },
      { country: 'United Arab Emirates', continent: 'Asia' },
      { country: 'United Kingdom', continent: 'Europe' },
      { country: 'Venezuela', continent: 'South America' },
      { country: 'Vietnam', continent: 'Asia' },
      { country: 'Czech Republic', continent: 'Europe' },
      { country: 'Hong Kong', continent: 'Asia' },
      { country: 'Puerto Rico', continent: 'North America' },
      { country: 'Russia', continent: 'Europe' },
      { country: 'Taiwan', continent: 'Asia' },
      { country: 'United States', continent: 'North America' }
    ].each do |country|
      Country.where(name: country[:country]).update_all(continent: country[:continent])
    end
  end

  def down
    remove_column :countries, :continent
  end
end
