# db/migrate/[timestamp]_create_bot_stats.rb
class CreateBotStats < ActiveRecord::Migration[6.0]
  def change
    create_table :bot_stats, id: :string, primary_key: :id do |t|
      t.integer "network_id"
      t.integer "offer_id"
      t.integer "offer_variant_id"
      t.integer "affiliate_id"
      t.string "subid_1"
      t.string "subid_2"
      t.string "subid_3"
      t.integer "language_id"
      t.string "http_user_agent"
      t.string "http_referer"
      t.string "ip_address"
      t.integer "clicks"
      t.integer "conversions"
      t.datetime "recorded_at", default: "1970-01-01 00:00:00", null: false
      t.decimal "true_pay", precision: 20, scale: 2
      t.decimal "affiliate_pay", precision: 20, scale: 2
      t.integer "affiliate_offer_id"
      t.string "manual_notes", limit: 500
      t.string "status"
      t.integer "image_creative_id"
      t.datetime "converted_at"
      t.datetime "created_at"
      t.datetime "updated_at"
      t.string "vtm_host"
      t.string "vtm_page"
      t.string "vtm_channel"
      t.integer "mkt_site_id"
      t.integer "hits"
      t.integer "mkt_url_id"
      t.string "vtm_campaign"
      t.string "ip_country"
      t.string "approval"
      t.integer "order_id"
      t.string "step_name"
      t.string "step_label"
      t.string "true_conv_type"
      t.string "affiliate_conv_type"
      t.integer "lead_id"
      t.string "s1"
      t.string "s2"
      t.string "s3"
      t.string "s4"
      t.boolean "is_bot", default: true
      t.integer "text_creative_id"
      t.integer "channel_id"
      t.integer "campaign_id"
      t.integer "ad_group_id"
      t.integer "ad_id"
      t.string "keyword"
      t.integer "share_creative_id"
      t.datetime "captured_at"
      t.string "isp"
      t.string "browser"
      t.string "browser_version"
      t.string "device_type"
      t.string "device_brand"
      t.string "device_model"
      t.string "aff_uniq_id"
      t.string "ios_uniq"
      t.string "android_uniq"
      t.string "subid_4"
      t.string "subid_5"
      t.string "order_number"
      t.string "gaid"
      t.integer "email_creative_id"
      t.decimal "qscore", precision: 10, scale: 2
      t.string "ad_slot_id"
      t.integer "impression"
      t.datetime "published_at"
      t.json "forex"
      t.string "original_currency", limit: 3
      t.string "adv_uniq_id"
      t.decimal "order_total", precision: 20, scale: 2

      t.index ["adv_uniq_id"], name: "index_bot_stats_on_adv_uniq_id"
      t.index ["aff_uniq_id"], name: "index_bot_stats_on_aff_uniq_id"
      t.index ["affiliate_id"], name: "index_bot_stats_on_affiliate_id"
      t.index ["captured_at"], name: "index_bot_stats_on_captured_at"
      t.index ["converted_at"], name: "index_bot_stats_on_converted_at"
      t.index ["id"], name: "index_bot_stats_on_id"
      t.index ["ip_address"], name: "index_bot_stats_on_ip_address"
      t.index ["network_id", "captured_at"], name: "index_bot_stats_on_network_id_and_captured_at"
      t.index ["network_id"], name: "index_bot_stats_on_network_id"
      t.index ["offer_id"], name: "index_bot_stats_on_offer_id"
      t.index ["order_id"], name: "index_bot_stats_on_order_id"
      t.index ["published_at"], name: "index_bot_stats_on_published_at"
      t.index ["subid_1"], name: "index_bot_stats_on_subid_1"
      t.index ["subid_2"], name: "index_bot_stats_on_subid_2"
      t.index ["subid_3"], name: "index_bot_stats_on_subid_3"
      t.index ["subid_4"], name: "index_bot_stats_on_subid_4"
      t.index ["subid_5"], name: "index_bot_stats_on_subid_5"
      t.index ["updated_at"], name: "index_bot_stats_on_updated_at"
    end
  end
end
